volumes:
  smoking-db:

services:
  database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - smoking-db:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    